### ISSUE TITLE
Better structure and more data

### ISSUE THREAD

**Issue by brunolemos** [datwheat/react-native-bet#10]
A list with company names might not be that useful when it gets big. We know nothing about them, their size, if they are relevant or not, etc.

How about something similar to this?

### Big companies

|  	| Company     	| About                                	| Founded 	| Adopted RN 	| Hiring 	|
|---------	|-------------	|--------------------------------------	|------------	|------------------	|------------------	|
| <div title="USA">🇺🇸</div>    	| [Facebook](https://facebook.com/?ref=react-native-bet)    	| Social Network; Created React Native 	| 2004       	| 2015             	| LOCAL             	|

### Startups

|  	| Company     	| About                                	| Founded 	| Adopted RN 	| Hiring 	|
|---------	|-------------	|--------------------------------------	|------------	|------------------	|------------------	|
| <div title="Sao Paulo, Brazil">🇧🇷</div>    	| [Easy Carros](https://easycarros.com/?ref=react-native-bet) 	| Car Services Delivery       	| 2015       	| 2016             	| LOCAL             	|
| <div title="Sao Paulo, Brazil">🇧🇷</div>    	| [Entria](https://www.entria.com.br/?ref=react-native-bet) 	| Software Development       	| 2017       	| Always             	| LOCAL<br/> REMOTE             	|

### Independent Developers

|  	| Company     	| About                                	| Founded 	| Adopted RN 	| Hiring 	|
|---------	|-------------	|--------------------------------------	|------------	|------------------	|------------------	|
| <div title="India">🇮🇳</div>    	| ... 	| ...       	| 2017       	| 2017             	| No             	|

### ...

**Comment by FiberJW** [comment]
I'm thinking about that idea, but I don't want it to be like hey there's Facebook Microsoft and Uber and everyone else. Keeping the list flat would mean for a more level "playing field" for discovery. The big companies will already be recognizable and if someone doesn't know what a name is, they can click a link and learn about it. The power of the hyperlink eh? 👌

**Comment by brunolemos** [comment]
@datwheat I'm pretty sure people would prefer a quick overview of the companies rather than having to click on tens of links :)

**Comment by FiberJW** [comment]
true true. mind submitting a PR with your suggested structure?

**Comment by FiberJW** [comment]
I just made a change that separated companies by type (consultancy, product, big name). Does that help?

**Comment by FiberJW** [comment]
I'm gonna close this unless you have any further concerns. Thanks for the input!
