### ISSUE TITLE
Add Driversnote

### ISSUE THREAD

**Issue by JonasWho** [datwheat/react-native-bet#18]
At Driversnote, we've created our Android app with RN and our iOS app is up next! :)
https://www.driversnote.com

**Comment by FiberJW** [comment]
That's awesome! Mind submitting a PR?

**Comment by JonasWho** [comment]
I tried, but I keep getting Authentication failed when I want to Publish it through Github Desktop.

**Comment by FiberJW** [comment]
You've gotta fork the project and make edits on your version, you can't clone and make edits on my version of the repo. https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by JonasWho** [comment]
Thank you! And sorry for the n00b'ing :)
